name: Main
on:
  workflow_dispatch:
    inputs:
      new:
        type: boolean
        description: "Is first deployment?"
        required: false
        default: false
  workflow_run:
    workflows: ["Deploy Feature Branch"]
    types:
      - completed
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' }}
    steps:
      - name: Hello world
        run: echo "Hello world"

  deploy:
    runs-on: ubuntu-latest
    if: ${{ (github.ref == 'refs/heads/main' && github.event_name != 'workflow_run') || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    steps:
      - name: Set Ref
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref_name }}
      - name: Hello world
        run: cat README.md
      - name: Is new?
        run: echo ${{ github.event.inputs.new }}
